### ISSUE TITLE
CMDI2HTML not working

### ISSUE THREAD

**Issue by nmeisinger** [SfS-ASCL/metadatatransformation#5]
Currently the transformation from CMDI to HTML does not work. The following error gets thrown on my PC:

    Error at xsl:include on line 24 column 38 
    XTSE0165: I/O error reported by XML parser processing
    file:/C:/Users/<Username>/<TomcatLocation>/apache-tomcat-9.0.46/bin/xsl/Utils.xsl:
    C:\Users\<Username>\<TomcatLocation>\apache-tomcat-9.0.46\bin\xsl\Utils.xsl (Das System kann den
    angegebenen Pfad nicht finden)`

The server is not looking for the xsl directory under `src/webapp`, but inside the local `bin` directory of the Tomcat server. Copying it into the `bin` directory causes a variety of new error messages.

Does this error occur, because I did not setup the project correctly on my PC or is it a general problem?

**Comment by wyleyr** [comment]
Hmm...it's probably a general problem. How are you building and running the server?

We probably just need to adjust a path in a configuration file somewhere but I can't find any such path at the moment.

**Comment by wyleyr** [comment]
@nmeisinger I have no experience with Tomcat so I can't be much help at the moment -- but if you can tell me how you're building and running the service (Maven?) I will test it locally.

Meanwhile here is a little help from @ttrippel:

Hhm, if Tomcat looks for them in a specific place on runtime, I wonder  which place this would be. My local Tomcasts logs say it looks for it in:

/usr/local/apache-tomcat-9.0.45/bin/Utils.xsl

So I tried to modify the include to start from the bin directory:   
```
<xsl:include href="../webapps/metadatatransformation1.0.8_dev/xsl/Utils.xsl"/>
```
In  ../webapps/metadatatransformation1.0.8_dev/xsl/ the metadatatransformation1.0.8_dev is the name of my war file. This is not a solution to the problem but we are coming closer....

So why is there a file/path problem? I found a hint at 
https://stackoverflow.com/questions/56535863/how-to-use-saxon-on-tomcat-9

This is about licence files for saxon, which is not directly relevant, but Michael Kay writes:

> The mechanism of simply putting the license file in the same folder as 
> the JAR file works in some environments but not others; it depends on 
> what class loader is used to load the Saxon classes (some class loaders 
> don't allow Saxon to discover the location that it was loaded from for 
> security reasons).

--> The problem seems to be the class loader.

I don't know if this will help in debugging though, but possibly it helps to set us on track.

**Comment by nmeisinger** [comment]
>I have no experience with Tomcat so I can't be much help at the moment -- but if you can tell me how you're building and running the service (Maven?) I will test it locally.

I build the project with Maven and deploy the resulting war file with Tomcat (my IntelliJ offers an automatic setup for it).

I also googled a bit and found a StackOverflow containing a hint on how to resolve the problem with the class loader:
https://stackoverflow.com/questions/4716299/xsl-import-causing-filenotfoundexception-in-web-application

>You need to provide a custom uri-resolver to process the includes. In a web application, there's no guarantee that a filesystem is accessible, as you could be running out of a WAR file. Take a look at the javax.xml.transform.URIResolver interface and Transformer.setURIResolver()

I'm gonna see if I can find a solution with this.

**Comment by wyleyr** [comment]
> my IntelliJ offers an automatic setup for it

Oh, you IDE people ;) No wonder I'm in the dark. I want a nice "make && ./build/runserver"...

Sounds like you're on the right track, but let us know if you get stuck!

**Comment by nmeisinger** [comment]
Found the problem:
The `webapp/xsl` directory needed to be specified in the pom.xml, as well as writing a custom class implementing the URIResolver interface
